spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=tenant
    username: sa
    password: 1A@d^c^p^
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080